version: "2"
run:
  concurrency: 4
  issues-exit-code: 1
  tests: true
linters:
  default: all
  disable:
    - bodyclose
    - cyclop
    - depguard
    - dogsled
    - dupl
    - err113
    - errname
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocyclo
    - godox
    - gosec
    - gosmopolitan
    - inamedparam
    - interfacebloat
    - ireturn
    - lll
    - maintidx
    - makezero
    - mnd
    - modernize
    - musttag
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - revive
    - tagliatelle
    - testifylint
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    dupl:
      threshold: 150
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-checks:
        - builtinShadow
        - nilValReturn
        - rangeExprCopy
        - rangeValCopy
        - typeUnparen
    gocyclo:
      min-complexity: 29
    lll:
      line-length: 120
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - gocyclo
          - godot
          - gosec
          - testpackage
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
      - cmd/playground
      - cmd/miniscript
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
