// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hww.proto

package messages

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_c12bd9e6412b8a05, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Success struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Success) Reset()         { *m = Success{} }
func (m *Success) String() string { return proto.CompactTextString(m) }
func (*Success) ProtoMessage()    {}
func (*Success) Descriptor() ([]byte, []int) {
	return fileDescriptor_c12bd9e6412b8a05, []int{1}
}

func (m *Success) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Success.Unmarshal(m, b)
}
func (m *Success) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Success.Marshal(b, m, deterministic)
}
func (m *Success) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Success.Merge(m, src)
}
func (m *Success) XXX_Size() int {
	return xxx_messageInfo_Success.Size(m)
}
func (m *Success) XXX_DiscardUnknown() {
	xxx_messageInfo_Success.DiscardUnknown(m)
}

var xxx_messageInfo_Success proto.InternalMessageInfo

type Request struct {
	// Types that are valid to be assigned to Request:
	//	*Request_DeviceName
	//	*Request_DeviceLanguage
	//	*Request_DeviceInfo
	//	*Request_SetPassword
	//	*Request_CreateBackup
	//	*Request_ShowMnemonic
	//	*Request_BtcPub
	//	*Request_BtcSignInit
	//	*Request_BtcSignInput
	//	*Request_BtcSignOutput
	//	*Request_InsertRemoveSdcard
	//	*Request_CheckSdcard
	//	*Request_SetMnemonicPassphraseEnabled
	//	*Request_ListBackups
	//	*Request_RestoreBackup
	//	*Request_PerformAttestation
	//	*Request_Reboot
	//	*Request_CheckBackup
	//	*Request_Eth
	//	*Request_Reset_
	//	*Request_RestoreFromMnemonic
	//	*Request_Fingerprint
	//	*Request_Btc
	//	*Request_ElectrumEncryptionKey
	Request              isRequest_Request `protobuf_oneof:"request"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_c12bd9e6412b8a05, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type isRequest_Request interface {
	isRequest_Request()
}

type Request_DeviceName struct {
	DeviceName *SetDeviceNameRequest `protobuf:"bytes,2,opt,name=device_name,json=deviceName,proto3,oneof"`
}

type Request_DeviceLanguage struct {
	DeviceLanguage *SetDeviceLanguageRequest `protobuf:"bytes,3,opt,name=device_language,json=deviceLanguage,proto3,oneof"`
}

type Request_DeviceInfo struct {
	DeviceInfo *DeviceInfoRequest `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,proto3,oneof"`
}

type Request_SetPassword struct {
	SetPassword *SetPasswordRequest `protobuf:"bytes,5,opt,name=set_password,json=setPassword,proto3,oneof"`
}

type Request_CreateBackup struct {
	CreateBackup *CreateBackupRequest `protobuf:"bytes,6,opt,name=create_backup,json=createBackup,proto3,oneof"`
}

type Request_ShowMnemonic struct {
	ShowMnemonic *ShowMnemonicRequest `protobuf:"bytes,7,opt,name=show_mnemonic,json=showMnemonic,proto3,oneof"`
}

type Request_BtcPub struct {
	BtcPub *BTCPubRequest `protobuf:"bytes,8,opt,name=btc_pub,json=btcPub,proto3,oneof"`
}

type Request_BtcSignInit struct {
	BtcSignInit *BTCSignInitRequest `protobuf:"bytes,9,opt,name=btc_sign_init,json=btcSignInit,proto3,oneof"`
}

type Request_BtcSignInput struct {
	BtcSignInput *BTCSignInputRequest `protobuf:"bytes,10,opt,name=btc_sign_input,json=btcSignInput,proto3,oneof"`
}

type Request_BtcSignOutput struct {
	BtcSignOutput *BTCSignOutputRequest `protobuf:"bytes,11,opt,name=btc_sign_output,json=btcSignOutput,proto3,oneof"`
}

type Request_InsertRemoveSdcard struct {
	InsertRemoveSdcard *InsertRemoveSDCardRequest `protobuf:"bytes,12,opt,name=insert_remove_sdcard,json=insertRemoveSdcard,proto3,oneof"`
}

type Request_CheckSdcard struct {
	CheckSdcard *CheckSDCardRequest `protobuf:"bytes,13,opt,name=check_sdcard,json=checkSdcard,proto3,oneof"`
}

type Request_SetMnemonicPassphraseEnabled struct {
	SetMnemonicPassphraseEnabled *SetMnemonicPassphraseEnabledRequest `protobuf:"bytes,14,opt,name=set_mnemonic_passphrase_enabled,json=setMnemonicPassphraseEnabled,proto3,oneof"`
}

type Request_ListBackups struct {
	ListBackups *ListBackupsRequest `protobuf:"bytes,15,opt,name=list_backups,json=listBackups,proto3,oneof"`
}

type Request_RestoreBackup struct {
	RestoreBackup *RestoreBackupRequest `protobuf:"bytes,16,opt,name=restore_backup,json=restoreBackup,proto3,oneof"`
}

type Request_PerformAttestation struct {
	PerformAttestation *PerformAttestationRequest `protobuf:"bytes,17,opt,name=perform_attestation,json=performAttestation,proto3,oneof"`
}

type Request_Reboot struct {
	Reboot *RebootRequest `protobuf:"bytes,18,opt,name=reboot,proto3,oneof"`
}

type Request_CheckBackup struct {
	CheckBackup *CheckBackupRequest `protobuf:"bytes,19,opt,name=check_backup,json=checkBackup,proto3,oneof"`
}

type Request_Eth struct {
	Eth *ETHRequest `protobuf:"bytes,20,opt,name=eth,proto3,oneof"`
}

type Request_Reset_ struct {
	Reset_ *ResetRequest `protobuf:"bytes,21,opt,name=reset,proto3,oneof"`
}

type Request_RestoreFromMnemonic struct {
	RestoreFromMnemonic *RestoreFromMnemonicRequest `protobuf:"bytes,22,opt,name=restore_from_mnemonic,json=restoreFromMnemonic,proto3,oneof"`
}

type Request_Fingerprint struct {
	Fingerprint *RootFingerprintRequest `protobuf:"bytes,24,opt,name=fingerprint,proto3,oneof"`
}

type Request_Btc struct {
	Btc *BTCRequest `protobuf:"bytes,25,opt,name=btc,proto3,oneof"`
}

type Request_ElectrumEncryptionKey struct {
	ElectrumEncryptionKey *ElectrumEncryptionKeyRequest `protobuf:"bytes,26,opt,name=electrum_encryption_key,json=electrumEncryptionKey,proto3,oneof"`
}

func (*Request_DeviceName) isRequest_Request() {}

func (*Request_DeviceLanguage) isRequest_Request() {}

func (*Request_DeviceInfo) isRequest_Request() {}

func (*Request_SetPassword) isRequest_Request() {}

func (*Request_CreateBackup) isRequest_Request() {}

func (*Request_ShowMnemonic) isRequest_Request() {}

func (*Request_BtcPub) isRequest_Request() {}

func (*Request_BtcSignInit) isRequest_Request() {}

func (*Request_BtcSignInput) isRequest_Request() {}

func (*Request_BtcSignOutput) isRequest_Request() {}

func (*Request_InsertRemoveSdcard) isRequest_Request() {}

func (*Request_CheckSdcard) isRequest_Request() {}

func (*Request_SetMnemonicPassphraseEnabled) isRequest_Request() {}

func (*Request_ListBackups) isRequest_Request() {}

func (*Request_RestoreBackup) isRequest_Request() {}

func (*Request_PerformAttestation) isRequest_Request() {}

func (*Request_Reboot) isRequest_Request() {}

func (*Request_CheckBackup) isRequest_Request() {}

func (*Request_Eth) isRequest_Request() {}

func (*Request_Reset_) isRequest_Request() {}

func (*Request_RestoreFromMnemonic) isRequest_Request() {}

func (*Request_Fingerprint) isRequest_Request() {}

func (*Request_Btc) isRequest_Request() {}

func (*Request_ElectrumEncryptionKey) isRequest_Request() {}

func (m *Request) GetRequest() isRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Request) GetDeviceName() *SetDeviceNameRequest {
	if x, ok := m.GetRequest().(*Request_DeviceName); ok {
		return x.DeviceName
	}
	return nil
}

func (m *Request) GetDeviceLanguage() *SetDeviceLanguageRequest {
	if x, ok := m.GetRequest().(*Request_DeviceLanguage); ok {
		return x.DeviceLanguage
	}
	return nil
}

func (m *Request) GetDeviceInfo() *DeviceInfoRequest {
	if x, ok := m.GetRequest().(*Request_DeviceInfo); ok {
		return x.DeviceInfo
	}
	return nil
}

func (m *Request) GetSetPassword() *SetPasswordRequest {
	if x, ok := m.GetRequest().(*Request_SetPassword); ok {
		return x.SetPassword
	}
	return nil
}

func (m *Request) GetCreateBackup() *CreateBackupRequest {
	if x, ok := m.GetRequest().(*Request_CreateBackup); ok {
		return x.CreateBackup
	}
	return nil
}

func (m *Request) GetShowMnemonic() *ShowMnemonicRequest {
	if x, ok := m.GetRequest().(*Request_ShowMnemonic); ok {
		return x.ShowMnemonic
	}
	return nil
}

func (m *Request) GetBtcPub() *BTCPubRequest {
	if x, ok := m.GetRequest().(*Request_BtcPub); ok {
		return x.BtcPub
	}
	return nil
}

func (m *Request) GetBtcSignInit() *BTCSignInitRequest {
	if x, ok := m.GetRequest().(*Request_BtcSignInit); ok {
		return x.BtcSignInit
	}
	return nil
}

func (m *Request) GetBtcSignInput() *BTCSignInputRequest {
	if x, ok := m.GetRequest().(*Request_BtcSignInput); ok {
		return x.BtcSignInput
	}
	return nil
}

func (m *Request) GetBtcSignOutput() *BTCSignOutputRequest {
	if x, ok := m.GetRequest().(*Request_BtcSignOutput); ok {
		return x.BtcSignOutput
	}
	return nil
}

func (m *Request) GetInsertRemoveSdcard() *InsertRemoveSDCardRequest {
	if x, ok := m.GetRequest().(*Request_InsertRemoveSdcard); ok {
		return x.InsertRemoveSdcard
	}
	return nil
}

func (m *Request) GetCheckSdcard() *CheckSDCardRequest {
	if x, ok := m.GetRequest().(*Request_CheckSdcard); ok {
		return x.CheckSdcard
	}
	return nil
}

func (m *Request) GetSetMnemonicPassphraseEnabled() *SetMnemonicPassphraseEnabledRequest {
	if x, ok := m.GetRequest().(*Request_SetMnemonicPassphraseEnabled); ok {
		return x.SetMnemonicPassphraseEnabled
	}
	return nil
}

func (m *Request) GetListBackups() *ListBackupsRequest {
	if x, ok := m.GetRequest().(*Request_ListBackups); ok {
		return x.ListBackups
	}
	return nil
}

func (m *Request) GetRestoreBackup() *RestoreBackupRequest {
	if x, ok := m.GetRequest().(*Request_RestoreBackup); ok {
		return x.RestoreBackup
	}
	return nil
}

func (m *Request) GetPerformAttestation() *PerformAttestationRequest {
	if x, ok := m.GetRequest().(*Request_PerformAttestation); ok {
		return x.PerformAttestation
	}
	return nil
}

func (m *Request) GetReboot() *RebootRequest {
	if x, ok := m.GetRequest().(*Request_Reboot); ok {
		return x.Reboot
	}
	return nil
}

func (m *Request) GetCheckBackup() *CheckBackupRequest {
	if x, ok := m.GetRequest().(*Request_CheckBackup); ok {
		return x.CheckBackup
	}
	return nil
}

func (m *Request) GetEth() *ETHRequest {
	if x, ok := m.GetRequest().(*Request_Eth); ok {
		return x.Eth
	}
	return nil
}

func (m *Request) GetReset_() *ResetRequest {
	if x, ok := m.GetRequest().(*Request_Reset_); ok {
		return x.Reset_
	}
	return nil
}

func (m *Request) GetRestoreFromMnemonic() *RestoreFromMnemonicRequest {
	if x, ok := m.GetRequest().(*Request_RestoreFromMnemonic); ok {
		return x.RestoreFromMnemonic
	}
	return nil
}

func (m *Request) GetFingerprint() *RootFingerprintRequest {
	if x, ok := m.GetRequest().(*Request_Fingerprint); ok {
		return x.Fingerprint
	}
	return nil
}

func (m *Request) GetBtc() *BTCRequest {
	if x, ok := m.GetRequest().(*Request_Btc); ok {
		return x.Btc
	}
	return nil
}

func (m *Request) GetElectrumEncryptionKey() *ElectrumEncryptionKeyRequest {
	if x, ok := m.GetRequest().(*Request_ElectrumEncryptionKey); ok {
		return x.ElectrumEncryptionKey
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Request) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Request_DeviceName)(nil),
		(*Request_DeviceLanguage)(nil),
		(*Request_DeviceInfo)(nil),
		(*Request_SetPassword)(nil),
		(*Request_CreateBackup)(nil),
		(*Request_ShowMnemonic)(nil),
		(*Request_BtcPub)(nil),
		(*Request_BtcSignInit)(nil),
		(*Request_BtcSignInput)(nil),
		(*Request_BtcSignOutput)(nil),
		(*Request_InsertRemoveSdcard)(nil),
		(*Request_CheckSdcard)(nil),
		(*Request_SetMnemonicPassphraseEnabled)(nil),
		(*Request_ListBackups)(nil),
		(*Request_RestoreBackup)(nil),
		(*Request_PerformAttestation)(nil),
		(*Request_Reboot)(nil),
		(*Request_CheckBackup)(nil),
		(*Request_Eth)(nil),
		(*Request_Reset_)(nil),
		(*Request_RestoreFromMnemonic)(nil),
		(*Request_Fingerprint)(nil),
		(*Request_Btc)(nil),
		(*Request_ElectrumEncryptionKey)(nil),
	}
}

type Response struct {
	// Types that are valid to be assigned to Response:
	//	*Response_Success
	//	*Response_Error
	//	*Response_DeviceInfo
	//	*Response_Pub
	//	*Response_BtcSignNext
	//	*Response_ListBackups
	//	*Response_CheckBackup
	//	*Response_PerformAttestation
	//	*Response_CheckSdcard
	//	*Response_Eth
	//	*Response_Fingerprint
	//	*Response_Btc
	//	*Response_ElectrumEncryptionKey
	Response             isResponse_Response `protobuf_oneof:"response"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_c12bd9e6412b8a05, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

type isResponse_Response interface {
	isResponse_Response()
}

type Response_Success struct {
	Success *Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type Response_Error struct {
	Error *Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

type Response_DeviceInfo struct {
	DeviceInfo *DeviceInfoResponse `protobuf:"bytes,4,opt,name=device_info,json=deviceInfo,proto3,oneof"`
}

type Response_Pub struct {
	Pub *PubResponse `protobuf:"bytes,5,opt,name=pub,proto3,oneof"`
}

type Response_BtcSignNext struct {
	BtcSignNext *BTCSignNextResponse `protobuf:"bytes,6,opt,name=btc_sign_next,json=btcSignNext,proto3,oneof"`
}

type Response_ListBackups struct {
	ListBackups *ListBackupsResponse `protobuf:"bytes,7,opt,name=list_backups,json=listBackups,proto3,oneof"`
}

type Response_CheckBackup struct {
	CheckBackup *CheckBackupResponse `protobuf:"bytes,8,opt,name=check_backup,json=checkBackup,proto3,oneof"`
}

type Response_PerformAttestation struct {
	PerformAttestation *PerformAttestationResponse `protobuf:"bytes,9,opt,name=perform_attestation,json=performAttestation,proto3,oneof"`
}

type Response_CheckSdcard struct {
	CheckSdcard *CheckSDCardResponse `protobuf:"bytes,10,opt,name=check_sdcard,json=checkSdcard,proto3,oneof"`
}

type Response_Eth struct {
	Eth *ETHResponse `protobuf:"bytes,11,opt,name=eth,proto3,oneof"`
}

type Response_Fingerprint struct {
	Fingerprint *RootFingerprintResponse `protobuf:"bytes,12,opt,name=fingerprint,proto3,oneof"`
}

type Response_Btc struct {
	Btc *BTCResponse `protobuf:"bytes,13,opt,name=btc,proto3,oneof"`
}

type Response_ElectrumEncryptionKey struct {
	ElectrumEncryptionKey *ElectrumEncryptionKeyResponse `protobuf:"bytes,14,opt,name=electrum_encryption_key,json=electrumEncryptionKey,proto3,oneof"`
}

func (*Response_Success) isResponse_Response() {}

func (*Response_Error) isResponse_Response() {}

func (*Response_DeviceInfo) isResponse_Response() {}

func (*Response_Pub) isResponse_Response() {}

func (*Response_BtcSignNext) isResponse_Response() {}

func (*Response_ListBackups) isResponse_Response() {}

func (*Response_CheckBackup) isResponse_Response() {}

func (*Response_PerformAttestation) isResponse_Response() {}

func (*Response_CheckSdcard) isResponse_Response() {}

func (*Response_Eth) isResponse_Response() {}

func (*Response_Fingerprint) isResponse_Response() {}

func (*Response_Btc) isResponse_Response() {}

func (*Response_ElectrumEncryptionKey) isResponse_Response() {}

func (m *Response) GetResponse() isResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (m *Response) GetSuccess() *Success {
	if x, ok := m.GetResponse().(*Response_Success); ok {
		return x.Success
	}
	return nil
}

func (m *Response) GetError() *Error {
	if x, ok := m.GetResponse().(*Response_Error); ok {
		return x.Error
	}
	return nil
}

func (m *Response) GetDeviceInfo() *DeviceInfoResponse {
	if x, ok := m.GetResponse().(*Response_DeviceInfo); ok {
		return x.DeviceInfo
	}
	return nil
}

func (m *Response) GetPub() *PubResponse {
	if x, ok := m.GetResponse().(*Response_Pub); ok {
		return x.Pub
	}
	return nil
}

func (m *Response) GetBtcSignNext() *BTCSignNextResponse {
	if x, ok := m.GetResponse().(*Response_BtcSignNext); ok {
		return x.BtcSignNext
	}
	return nil
}

func (m *Response) GetListBackups() *ListBackupsResponse {
	if x, ok := m.GetResponse().(*Response_ListBackups); ok {
		return x.ListBackups
	}
	return nil
}

func (m *Response) GetCheckBackup() *CheckBackupResponse {
	if x, ok := m.GetResponse().(*Response_CheckBackup); ok {
		return x.CheckBackup
	}
	return nil
}

func (m *Response) GetPerformAttestation() *PerformAttestationResponse {
	if x, ok := m.GetResponse().(*Response_PerformAttestation); ok {
		return x.PerformAttestation
	}
	return nil
}

func (m *Response) GetCheckSdcard() *CheckSDCardResponse {
	if x, ok := m.GetResponse().(*Response_CheckSdcard); ok {
		return x.CheckSdcard
	}
	return nil
}

func (m *Response) GetEth() *ETHResponse {
	if x, ok := m.GetResponse().(*Response_Eth); ok {
		return x.Eth
	}
	return nil
}

func (m *Response) GetFingerprint() *RootFingerprintResponse {
	if x, ok := m.GetResponse().(*Response_Fingerprint); ok {
		return x.Fingerprint
	}
	return nil
}

func (m *Response) GetBtc() *BTCResponse {
	if x, ok := m.GetResponse().(*Response_Btc); ok {
		return x.Btc
	}
	return nil
}

func (m *Response) GetElectrumEncryptionKey() *ElectrumEncryptionKeyResponse {
	if x, ok := m.GetResponse().(*Response_ElectrumEncryptionKey); ok {
		return x.ElectrumEncryptionKey
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Response) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Response_Success)(nil),
		(*Response_Error)(nil),
		(*Response_DeviceInfo)(nil),
		(*Response_Pub)(nil),
		(*Response_BtcSignNext)(nil),
		(*Response_ListBackups)(nil),
		(*Response_CheckBackup)(nil),
		(*Response_PerformAttestation)(nil),
		(*Response_CheckSdcard)(nil),
		(*Response_Eth)(nil),
		(*Response_Fingerprint)(nil),
		(*Response_Btc)(nil),
		(*Response_ElectrumEncryptionKey)(nil),
	}
}

func init() {
	proto.RegisterType((*Error)(nil), "shiftcrypto.bitbox02.Error")
	proto.RegisterType((*Success)(nil), "shiftcrypto.bitbox02.Success")
	proto.RegisterType((*Request)(nil), "shiftcrypto.bitbox02.Request")
	proto.RegisterType((*Response)(nil), "shiftcrypto.bitbox02.Response")
}

func init() { proto.RegisterFile("hww.proto", fileDescriptor_c12bd9e6412b8a05) }

var fileDescriptor_c12bd9e6412b8a05 = []byte{
	// 1069 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x97, 0x5d, 0x53, 0xe3, 0x36,
	0x17, 0xc7, 0x97, 0x25, 0x90, 0x44, 0x49, 0x80, 0x47, 0xc0, 0xb3, 0x5a, 0xda, 0x4e, 0x29, 0xbd,
	0x28, 0xed, 0xb4, 0x74, 0x07, 0xca, 0xc5, 0x76, 0xa6, 0x9d, 0x29, 0x59, 0x76, 0x80, 0x5d, 0xb2,
	0xd9, 0x84, 0x9b, 0x5e, 0x79, 0x6c, 0xe5, 0x84, 0x78, 0x88, 0x25, 0x57, 0x92, 0x17, 0xb8, 0xed,
	0x37, 0xed, 0x4d, 0x3f, 0x47, 0x47, 0x92, 0x5f, 0x44, 0xb0, 0x4d, 0x7b, 0x67, 0x8e, 0xff, 0xe7,
	0x97, 0xa3, 0xa3, 0xf3, 0x62, 0x50, 0x7b, 0x76, 0x7b, 0x7b, 0x10, 0x0b, 0xae, 0x38, 0xde, 0x92,
	0xb3, 0x70, 0xaa, 0xa8, 0xb8, 0x8f, 0x15, 0x3f, 0x08, 0x42, 0x15, 0xf0, 0xbb, 0x57, 0x87, 0x3b,
	0x5d, 0xca, 0xa3, 0x88, 0x33, 0xab, 0xd9, 0xd9, 0x0e, 0x7c, 0x7a, 0x93, 0xc4, 0x9e, 0x36, 0xfa,
	0x6c, 0x22, 0x73, 0x73, 0x2a, 0xf7, 0xe4, 0xbd, 0x54, 0x10, 0xa5, 0xe6, 0x76, 0xa0, 0x68, 0xf6,
	0x08, 0x6a, 0x96, 0x3e, 0xae, 0xdd, 0xc0, 0xbd, 0x54, 0x5c, 0x40, 0xf6, 0x77, 0xc4, 0x20, 0xe2,
	0x2c, 0xcc, 0xa4, 0xdd, 0x07, 0x8c, 0x97, 0x31, 0x88, 0x29, 0x17, 0x91, 0xe7, 0x2b, 0x05, 0x52,
	0xf9, 0x2a, 0xcc, 0x82, 0xd9, 0x3b, 0x46, 0x2b, 0xa7, 0x42, 0x70, 0x81, 0x31, 0x6a, 0x50, 0x3e,
	0x01, 0xb2, 0xb4, 0xbb, 0xb4, 0xbf, 0x32, 0x32, 0xcf, 0x98, 0xa0, 0x66, 0x04, 0x52, 0xfa, 0xd7,
	0x40, 0x9e, 0xef, 0x2e, 0xed, 0xb7, 0x47, 0xd9, 0x9f, 0x7b, 0x6d, 0xd4, 0x1c, 0x27, 0x94, 0x82,
	0x94, 0x7b, 0x7f, 0xad, 0xa3, 0xe6, 0x08, 0xfe, 0x48, 0x40, 0x2a, 0x7c, 0x89, 0x3a, 0x13, 0xf8,
	0x14, 0x52, 0xf0, 0x98, 0x1f, 0x59, 0xa7, 0xce, 0xe1, 0x77, 0x07, 0x65, 0x49, 0x39, 0x18, 0x83,
	0x7a, 0x63, 0xb4, 0x03, 0x3f, 0x82, 0x14, 0x70, 0xf6, 0x6c, 0x84, 0x26, 0xb9, 0x11, 0xff, 0x8e,
	0xd6, 0x53, 0xdc, 0xdc, 0x67, 0xd7, 0x89, 0x8e, 0x63, 0xd9, 0x20, 0x0f, 0x9e, 0x40, 0xbe, 0x4f,
	0xe5, 0x05, 0x76, 0x6d, 0xf2, 0xe0, 0x05, 0xbe, 0xc8, 0x23, 0x0d, 0xd9, 0x94, 0x93, 0x86, 0xc1,
	0x7e, 0x53, 0x8e, 0xb5, 0xcc, 0x73, 0x36, 0xe5, 0x8f, 0xc2, 0xd4, 0x46, 0x7c, 0x89, 0xba, 0x12,
	0x94, 0x17, 0xfb, 0x52, 0xde, 0x72, 0x31, 0x21, 0x2b, 0x06, 0xb6, 0x5f, 0x19, 0xe3, 0x30, 0x15,
	0x16, 0xb4, 0x8e, 0x2c, 0xac, 0x78, 0x88, 0x7a, 0x54, 0x80, 0xaf, 0xc0, 0xb3, 0x85, 0x42, 0x56,
	0x0d, 0xef, 0xdb, 0x72, 0x5e, 0xdf, 0x48, 0x4f, 0x8c, 0xb2, 0x00, 0x76, 0xa9, 0x63, 0xd6, 0x44,
	0x39, 0xe3, 0xb7, 0x5e, 0x56, 0x24, 0xa4, 0x59, 0x47, 0x1c, 0xcf, 0xf8, 0xed, 0x65, 0xaa, 0x74,
	0x88, 0xd2, 0x31, 0xe3, 0x5f, 0x51, 0x33, 0x50, 0xd4, 0x8b, 0x93, 0x80, 0xb4, 0x0c, 0xeb, 0xeb,
	0x72, 0xd6, 0xc9, 0x55, 0x7f, 0x98, 0x04, 0x05, 0x65, 0x35, 0x50, 0x74, 0x98, 0x04, 0x78, 0x80,
	0x7a, 0xda, 0x5f, 0x86, 0xd7, 0xcc, 0x0b, 0x59, 0xa8, 0x48, 0xbb, 0x2e, 0x67, 0x27, 0x57, 0xfd,
	0x71, 0x78, 0xcd, 0xce, 0x59, 0xa8, 0x9c, 0x9c, 0x05, 0x8a, 0x66, 0x56, 0xfc, 0x11, 0xad, 0x39,
	0xbc, 0x38, 0x51, 0x04, 0xd5, 0x1d, 0x31, 0x07, 0xc6, 0x89, 0x43, 0xec, 0xe6, 0xc4, 0x38, 0x51,
	0xf8, 0x0a, 0xad, 0xe7, 0x48, 0x9e, 0x28, 0xcd, 0xec, 0xd4, 0xd5, 0x73, 0xca, 0xfc, 0x60, 0xa4,
	0x05, 0xb4, 0x97, 0x42, 0xad, 0x1d, 0x53, 0xb4, 0x15, 0x32, 0x09, 0x42, 0x79, 0x02, 0x22, 0xfe,
	0x09, 0x3c, 0x39, 0xa1, 0xbe, 0x98, 0x90, 0xae, 0x41, 0xff, 0x58, 0x8e, 0x3e, 0x37, 0x1e, 0x23,
	0xe3, 0x30, 0x7e, 0xd3, 0xf7, 0xdd, 0xd2, 0xc1, 0xa1, 0xfb, 0xd2, 0xc0, 0x74, 0x41, 0xd2, 0x19,
	0xd0, 0x9b, 0x0c, 0xde, 0xab, 0x4b, 0x6e, 0x5f, 0x2b, 0x17, 0xa9, 0x1d, 0xe3, 0x9f, 0xe2, 0xfe,
	0x5c, 0x42, 0x5f, 0xea, 0x02, 0xcf, 0xca, 0xc7, 0x54, 0x7a, 0x3c, 0x13, 0xbe, 0x04, 0x0f, 0x98,
	0x1f, 0xcc, 0x61, 0x42, 0xd6, 0xcc, 0x4f, 0xbc, 0xae, 0xac, 0xf9, 0xac, 0x72, 0x86, 0xb9, 0xeb,
	0xa9, 0xf5, 0x2c, 0x7e, 0xf3, 0x73, 0x59, 0x23, 0xd3, 0x67, 0x9a, 0x87, 0x52, 0xa5, 0x3d, 0x21,
	0xc9, 0x7a, 0xdd, 0x99, 0xde, 0x87, 0x52, 0xd9, 0xda, 0x97, 0xce, 0x99, 0xe6, 0x85, 0x15, 0x8f,
	0xd1, 0x9a, 0x00, 0x33, 0x41, 0xb3, 0x2e, 0xdb, 0xa8, 0xbb, 0xdc, 0x91, 0xd5, 0x2e, 0xb6, 0x59,
	0x4f, 0xb8, 0x76, 0x1c, 0xa0, 0xcd, 0x92, 0x49, 0x4b, 0xfe, 0x57, 0x77, 0xb7, 0x43, 0xeb, 0xf0,
	0x5b, 0xa1, 0x77, 0xee, 0x36, 0x7e, 0xf4, 0x12, 0xff, 0x82, 0x56, 0x05, 0x04, 0x9c, 0x2b, 0x82,
	0xeb, 0x1a, 0x6f, 0x64, 0x34, 0x4e, 0xe3, 0x59, 0xa7, 0xa2, 0x34, 0xd2, 0x53, 0x6f, 0x3e, 0x59,
	0x1a, 0x8b, 0x67, 0xb6, 0xa5, 0x91, 0x9e, 0xf8, 0x27, 0xb4, 0x0c, 0x6a, 0x46, 0xb6, 0x0c, 0x65,
	0xb7, 0x9c, 0x72, 0x7a, 0x75, 0x56, 0x78, 0x6b, 0x39, 0xfe, 0x19, 0xad, 0x08, 0x90, 0xa0, 0xc8,
	0xb6, 0xf1, 0xdb, 0xab, 0xcc, 0x39, 0x38, 0x27, 0xb0, 0x2e, 0x78, 0x8a, 0xb6, 0xb3, 0x8b, 0x9b,
	0x0a, 0x1e, 0x15, 0x33, 0xed, 0xff, 0x86, 0xf5, 0xaa, 0xf6, 0xfe, 0xde, 0x0a, 0x1e, 0x3d, 0x1e,
	0x6d, 0x9b, 0xe2, 0xf1, 0x5b, 0x3c, 0x44, 0x9d, 0x69, 0xc8, 0xae, 0x41, 0xc4, 0x22, 0x64, 0x8a,
	0x10, 0x43, 0xff, 0xbe, 0x82, 0xce, 0xb9, 0x7a, 0x5b, 0x88, 0x9d, 0x5c, 0x39, 0x08, 0x9d, 0xab,
	0x40, 0x51, 0xf2, 0xb2, 0x2e, 0x57, 0x27, 0x57, 0x7d, 0x27, 0x57, 0x81, 0xa2, 0x78, 0x8e, 0x5e,
	0xc0, 0x1c, 0xa8, 0x12, 0x49, 0xe4, 0x01, 0x33, 0xfa, 0x90, 0x33, 0xef, 0x06, 0xee, 0xc9, 0x8e,
	0x21, 0x1d, 0x56, 0x64, 0x3d, 0x75, 0x3a, 0xcd, 0x7d, 0xde, 0xc1, 0x7d, 0xc1, 0xde, 0x86, 0xb2,
	0xf7, 0x27, 0x6d, 0xd4, 0x14, 0x56, 0x73, 0xd1, 0x68, 0x2d, 0x6d, 0x3c, 0xbf, 0x68, 0xb4, 0x5e,
	0x6c, 0x90, 0xbd, 0xbf, 0x9b, 0xa8, 0x35, 0x02, 0x19, 0x73, 0x26, 0x01, 0xbf, 0x46, 0x4d, 0x69,
	0x77, 0xbf, 0xf9, 0x58, 0xe8, 0x1c, 0x7e, 0x51, 0xd1, 0xf5, 0x56, 0x74, 0xf6, 0x6c, 0x94, 0xe9,
	0xf1, 0x11, 0x5a, 0x01, 0xfd, 0xb5, 0x91, 0x7e, 0x19, 0x7c, 0x56, 0x11, 0xba, 0x96, 0xe8, 0x1b,
	0x37, 0x5a, 0xfc, 0xae, 0x6c, 0x55, 0xef, 0x3f, 0xbd, 0xaa, 0x6d, 0xb8, 0x0b, 0xbb, 0xfa, 0x18,
	0x2d, 0xeb, 0xa5, 0x65, 0x57, 0xf4, 0x57, 0x15, 0x2d, 0xa9, 0x37, 0x56, 0xee, 0xad, 0xf5, 0xf8,
	0x83, 0xb3, 0xaf, 0x18, 0xdc, 0xa9, 0xfa, 0x9d, 0x9c, 0xae, 0x82, 0x01, 0xdc, 0x29, 0x07, 0x94,
	0x2d, 0x2c, 0x6d, 0xc6, 0x83, 0x85, 0x71, 0x56, 0xbb, 0x91, 0x1f, 0x8c, 0xb3, 0x82, 0xe7, 0xce,
	0xb3, 0xc1, 0x42, 0x5f, 0xb7, 0x6a, 0xbf, 0x19, 0xdc, 0xbe, 0x2e, 0x78, 0x6e, 0x63, 0xd3, 0xf2,
	0x51, 0xd6, 0xae, 0x6b, 0xb2, 0xb2, 0x51, 0x96, 0xd3, 0xcb, 0x66, 0xd9, 0x60, 0x61, 0x4f, 0xa1,
	0x27, 0x83, 0xce, 0xf6, 0xd4, 0x42, 0xd0, 0xe9, 0xa2, 0x3a, 0xb6, 0xd3, 0xa8, 0x53, 0x77, 0xb9,
	0x66, 0x1a, 0x15, 0x97, 0xab, 0xc7, 0xd1, 0xc7, 0x87, 0xad, 0x6e, 0x57, 0xf1, 0x0f, 0xff, 0xb2,
	0xd5, 0x8b, 0x48, 0xdc, 0x5e, 0x3f, 0xb6, 0xbd, 0xde, 0xab, 0x8b, 0xc4, 0xf4, 0x7a, 0x11, 0x89,
	0x6e, 0xf6, 0xa8, 0xba, 0xd9, 0xed, 0x82, 0x3d, 0xfa, 0x4f, 0xcd, 0x9e, 0xc3, 0x2b, 0xba, 0x1d,
	0xa1, 0x96, 0x48, 0x45, 0x17, 0x8d, 0xd6, 0xf2, 0x46, 0x23, 0x58, 0x35, 0xff, 0x15, 0x1c, 0xfd,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x83, 0x8a, 0xb9, 0xf8, 0xd3, 0x0c, 0x00, 0x00,
}
